#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname);
const PHOTOS = path.join(ROOT, 'photos');
const CONFIG_PATH = path.join(ROOT, 'config.json');
const DATA_JS_PATH = path.join(ROOT, 'data.js');

const ext = (f) => path.extname(f).toLowerCase();
const isMedia = (f) => ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.mp4', '.webm', '.mov', '.ogg'].includes(ext(f));

function escapeJs(s) {
  if (s == null) return 'null';
  return '"' + String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r') + '"';
}

const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
const dirs = fs.readdirSync(PHOTOS)
  .filter((f) => {
    const p = path.join(PHOTOS, f);
    return fs.statSync(p).isDirectory() && /^\d+$/.test(f);
  })
  .sort((a, b) => Number(a) - Number(b));

const reasons = [];
for (const d of dirs) {
  const dirPath = path.join(PHOTOS, d);
  const files = fs.readdirSync(dirPath);
  const mediaFile = files.find((f) => f !== 'text.txt' && f !== 'story.txt' && isMedia(f));
  if (!mediaFile) continue;
  const textPath = path.join(dirPath, 'text.txt');
  const storyPath = path.join(dirPath, 'story.txt');
  const text = fs.existsSync(textPath) ? fs.readFileSync(textPath, 'utf8').trim() : '';
  const story = fs.existsSync(storyPath) ? fs.readFileSync(storyPath, 'utf8').trim() : '';
  const image = 'photos/' + d + '/' + mediaFile;
  const reason = { image, text };
  if (story) reason.story = story;
  reasons.push(reason);
}

const lines = [
  '// Generated by build.js from config.json + photos/1, 2, 3...',
  'const CONFIG = {',
  '  partnerName: ' + escapeJs(config.partnerName) + ',',
  '  title: ' + escapeJs(config.title) + ',',
  '  music: ' + escapeJs(config.music) + ',',
  '  reasons: ['
];
reasons.forEach((r, i) => {
  lines.push('    {');
  lines.push('      image: ' + escapeJs(r.image) + ',');
  lines.push('      text: ' + escapeJs(r.text) + (r.story ? ',' : ''));
  if (r.story) lines.push('      story: ' + escapeJs(r.story));
  lines.push('    }' + (i < reasons.length - 1 ? ',' : ''));
});
lines.push('  ],');
lines.push('  closing: {');
lines.push('    text: ' + escapeJs(config.closing.text) + ',');
lines.push('    subtext: ' + escapeJs(config.closing.subtext));
lines.push('  }');
lines.push('};');

fs.writeFileSync(DATA_JS_PATH, lines.join('\n') + '\n', 'utf8');
console.log('data.js written with', reasons.length, 'reasons from photos/1..' + dirs[dirs.length - 1]);